version: "3"
services:
  app:
    build: .
    image: finance_tracker_backend
    depends_on:
      - postgres
    environment:
    #   DATABASE_URL: postgres://a9503664:null@postgres:5432/finance_tracker
      PORT: 3010
    container_name: backend
    networks:
     - default
    ports:
      - "3010:3010"
    command: npm run start-dev
    volumes:
      - .:/srv/app/nickylai-admin-server/
      - /srv/app/nickylai-admin-server/node_modules

  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    container_name: db
    networks:
      - default
    environment:
      POSTGRES_USER: a9503664
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance_tracker
networks:
  default:
    external:
      name: client_default
